---
# These are the collections required by the builder
collections:
- awx.awx
- ansible.controller
- ansible.netcommon
- ansible.posix
- ansible.utils
- azure.azcollection
- community.general
- community.aws
- containers.podman
- redhat_cop.controller_configuration
- redhat.rhel_idm
- redhat.rhel_system_roles
- redhat.satellite
- redhat.satellite_operations
- redhat.redhat_csp_download
